config/routes.rb
Rails.application.routes.draw do
  root 'pages#home'
  get 'pages/home'
  devise_for :users, :controllers => {:registrations => :registrations}
  resources :users do
  resources :profiles
  end
  resources :accountinfo
  resources :products do
    resources :comments
  end

  resources :relationships
  get 'preferences', to: 'products#preferences'
  get 'profiles', to: 'pages#profiles'
  get 'following', to: 'pages#following'
  get 'search', to: 'products#search'

  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

app/models/profile.rb
class Profile < ApplicationRecord
  belongs_to :user
  has_many :active_relationships, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  has_many :passive_relationships, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy
  has_many :followed_users, through: :active_relationships, source: :followed_user
  has_many :follower_users, through: :passive_relationships, source: :follower_user
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  def index
  @user = User.find(params[:user_id])
  @profile = @user.profile
end

# GET /users/1/profiles/1
def show
@user = User.find(params[:user_id])
# For URL like /movies/1/reviews/2
# Find an review in movies 1 that has id=2
@profile = @user.profile
@current = current_user
@userproducts = @user.products
@user_decorator = helpers.decorate(current_user)
@following = @user.active_relationships
end

# GET /users/1/profiles/new
def new
@user = User.find(params[:user_id])
# Associate an review object with movie 1
@profile = @user.build_profile
end

# POST /movies/1/reviews
def create
@user = User.find(params[:user_id])
@profile = @user.build_profile(params.require(:profile).permit(:name , :gender, :age, :location))
if @profile.save

redirect_to user_profile_url(@user, @profile)
else
render :action => "new"
end

end







end

app/helpers/profile_helper.rb
module ProfileHelper
end

app/views/profiles/_form.html.erb
<%= form_for([@user, @profile]) do |f| %>
<% if @user.errors.any? %>
<div id="error_explanation">
<h2><%= pluralize(@user.errors.count, "error")%>
prohibited this review from being saved:</h2>
<ul>
<% @profile.errors.full_messages.each do |msg| %>
<li><%= msg %></li>
<% end %>
</ul>
</div>
<% end %>
<div class="field">
<p>
<%= f.label :Name %><br />
<%= f.text_field :name %>
</p>
<p>
<%= f.label :Gender %><br />
<%= f.text_field :gender %>
</p>
<p>
<%= f.label :Age %><br />
<%= f.text_field :age %>
</p>
<p>
<%= f.label :Location %><br />
<%= f.text_field :location %>
</p>
</div>
<div class="actions">
<%= f.submit %>
</div>
<% end %>

app/views/profiles/index.html.erb
<h1>User Profile</h1>
<h1><%= @user.email %></h1>

app/views/profiles/new.html.erb
<h1>New profile</h1>
<%= render 'form' %>

app/views/profiles/show.html.erb
<b>User Profile Page</b> <br>
<%= hidden_field_tag :authenticity_token, form_authenticity_token %>
<span class="badge badge-pill badge-primary">Name: <%= @profile.name if @user.profile %></span> <br>
<span class="badge badge-pill badge-primary">Age: <%= @profile.age if @user.profile %></span>  <br>
<span class="badge badge-pill badge-primary">Gender: <%= @profile.gender if @user.profile %></span> <br>
<span class="badge badge-pill badge-primary">Location: <%= @profile.location if @user.profile %></span> <br>
<span class="badge badge-pill badge-primary">Followers: <%= @user.followers.count if @user.profile %></span> <br>


  <% if user_signed_in?%>
  <% if current_user.following?(@user)%>
  <%= button_to "Unfollow", relationship_path(user_id: @user.id), :method => :delete, class: 'btn btn-primary' %>
  <% else %>
  <%= button_to "Follow", relationships_path(user_id: @user.id) , class: 'btn btn-primary' %>
  <% end %>
  <% end %>
 
<div class="row">
<% @userproducts.each do |product| %>
<div class ="col-lg-4">
<div class="card" style="width: 13rem;">
<img src=https://www.bestbuysoccer.com/media/catalog/product/cache/1/image/510x/602f0fa2c1f0d1ba5e241f914e856ff9/t/-/t-shirt-men-blank-cotton-tee-shirt-man-tshirts-bodybuilding-bulk-plain-chemise-white-crew-neck.jpg class="card-img-top" alt="...">
<div class="card-body">
<h5 class="card-title"><%= product.name %></h5>
<p class="card-text"><%= product.description %></p>
<p class="card-text"><%= product.user.username %></p>
<a href="http://localhost:3000/products/<%= product.id %>"  class="btn btn-primary">View Product</a>
</div>
</div>
</div>
<% end %>

</div>