config/routes.rb
Rails.application.routes.draw do
  root 'pages#home'
  get 'pages/home'
  devise_for :users, :controllers => {:registrations => :registrations}
  resources :users do
  resources :profiles
  end
  resources :accountinfo
  resources :products do
    resources :comments
  end

  resources :relationships
  get 'preferences', to: 'products#preferences'
  get 'profiles', to: 'pages#profiles'
  get 'following', to: 'pages#following'
  get 'search', to: 'products#search'

  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

app/models/product.rb
class Product < ActiveRecord::Base
  belongs_to :user
  has_many :comments
end

app/controllers/products_controller.rb
require 'uri'
require 'net/http'
require 'openssl'
require 'json'
require 'ostruct'
class ProductsController < ApplicationController

  before_action :set_product, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:show, :index]
  # GET /products
  # GET /products.json
  def index
    @products = Product.all
  end

  def search
    @products = Product.where("name LIKE ?", "%" + params[:q] + "%")
    apiproducts = f21request(params[:q])
    @apiproducts = apiproducts
  end

  def preferences
    pref = amazonrequest()
    @clothing_preference = pref
  end

  def f21request(query)
    url = URI("https://apidojo-forever21-v1.p.rapidapi.com/products/search?color_groups=black&start=0&rows=15&query=#{query}")

    http = Net::HTTP.new(url.host, url.port)
    http.use_ssl = true
    http.verify_mode = OpenSSL::SSL::VERIFY_NONE

    request = Net::HTTP::Get.new(url)
    request["x-rapidapi-host"] = 'apidojo-forever21-v1.p.rapidapi.com'
    request["x-rapidapi-key"] = 'fpPGBGyACNmshJMcun5TDd492NwCp1RoE0Ljsn1QAJu4MuB0Lr'

    response = http.request(request)
    data = JSON.parse(response.read_body, object_class:OpenStruct)
    return data
  end

  def amazonrequest()

    url = URI("https://amazon-price1.p.rapidapi.com/search?keywords=#{current_user.clothing_preference}&marketplace=ES")

    http = Net::HTTP.new(url.host, url.port)
    http.use_ssl = true
    http.verify_mode = OpenSSL::SSL::VERIFY_NONE

    request = Net::HTTP::Get.new(url)
    request["x-rapidapi-host"] = 'amazon-price1.p.rapidapi.com'
    request["x-rapidapi-key"] = 'fpPGBGyACNmshJMcun5TDd492NwCp1RoE0Ljsn1QAJu4MuB0Lr'

    response = http.request(request)
    data = JSON.parse(response.read_body, object_class:OpenStruct)
    return data
  end


  # GET /products/1
  # GET /products/1.json
  def show
  end


  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)
    @product.user = current_user
    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:name, :description)
    end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_form.html.erb
<%= form_with(model: product, local: true) do |form| %>
  <% if product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% product.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_field :description %>
  </div>

  <%= form.label "Clothing Picture" %>
  <%= form.file_field :avatar %><br>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/products/_product.html.erb
<%= form_with(model: product, local: true) do |form| %>
  <% if product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% product.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_field :description %>
  </div>

<% end %>

app/views/products/edit.html.erb
<h1>Editing Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Products</h1>

    <div class="row">
  <% @products.each do |product| %>
  <div class ="col-lg-4">
  <div class="card" style="width: 13rem;">
  <img src=https://www.bestbuysoccer.com/media/catalog/product/cache/1/image/510x/602f0fa2c1f0d1ba5e241f914e856ff9/t/-/t-shirt-men-blank-cotton-tee-shirt-man-tshirts-bodybuilding-bulk-plain-chemise-white-crew-neck.jpg class="card-img-top" alt="...">
  <div class="card-body">
    <h5 class="card-title"><%= product.name %></h5>
    <p class="card-text"><%= product.description %></p>
    <p class="card-text"><%= product.user.username %></p>
    <a href="/products/<%= product.id %>"  class="btn btn-primary">View Product</a>
  </div>
  </div>
  </div>
  <% end %>
  </div>


<%= link_to 'New Product', new_product_path %>

app/views/products/new.html.erb
<h1>New Product</h1>

<%= render 'form', product: @product %>


<%= link_to 'Back', products_path %>

app/views/products/preferences.html.erb
<h1>Products for your preference</h1>
<div class="row">
<% @clothing_preference.each do |product| %>
<div class ="col-lg-4">
<div class="card" style="width: 18rem;">
  <img src=<%= product.imageUrl %> class="card-img-top" alt="...">
  <div class="card-body">
    <h5 class="card-title"><%= product.title %></h5>
    <p class="card-text"><%= product.price %></p>
    <a href=<%= product.detailPageURL %> class="btn btn-primary">Vist Amazon</a>
  </div>
</div>
</div>
<% end %>
</div>

app/views/products/search.html.erb
<h1>Search Result</h1>
<div class="row">
<% @apiproducts.response.docs.each do |product| %>
<div class ="col-lg-4">
<div class="card" style="width: 18rem;">
  <img src=<%= product.thumb_image %> class="card-img-top" alt="...">
  <div class="card-body">
    <h5 class="card-title"><%= product.title %></h5>
    <h5 class="card-title">Price <%= product.price %></h5>
    <h5 class="card-title">Sale Price<%= product.sale_price %></h5>
    <p class="card-text"><%= product.brand %></p>
    <a href=<%= product.url %> class="btn btn-primary">Vist Website</a>
  </div>
</div>
</div>
<% end %>
</div>

app/views/products/show.html.erb
<p>
  <strong>Name:</strong>
  <%= @product.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @product.description %>
</p>

<p>
  <strong>User:</strong>
  <%= @product.user.email %>
</p>
<br>
<h3>Add a comment</h3>
<strong> <%= @product.comments.count %> Comments </strong>
<%= render @product.comments %>
<%= render 'comments/form' %>
<%= link_to 'Edit', edit_product_path(@product) %> |
<%= link_to 'Back', products_path %>